package io.github.inoutch.kotlin.vulkan.api

enum class VkMemoryHeapFlagBits(val bit: Int) {
    VK_MEMORY_HEAP_DEVICE_LOCAL_BIT(0x00000001),
    VK_MEMORY_HEAP_MULTI_INSTANCE_BIT(0x00000002),
    VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR(VK_MEMORY_HEAP_MULTI_INSTANCE_BIT.bit),
    VK_MEMORY_HEAP_FLAG_BITS_MAX_ENUM(0x7FFFFFFF),
}
