package io.github.inoutch.kotlin.vulkan.api

import io.github.inoutch.kotlin.vulkan.extension.toFloatArray
import io.github.inoutch.kotlin.vulkan.extension.toIntArray

fun org.lwjgl.vulkan.VkPhysicalDeviceLimits.toOrigin(): VkPhysicalDeviceLimits {
    return VkPhysicalDeviceLimits(
            maxImageDimension1D(),
            maxImageDimension2D(),
            maxImageDimension3D(),
            maxImageDimensionCube(),
            maxImageArrayLayers(),
            maxTexelBufferElements(),
            maxUniformBufferRange(),
            maxStorageBufferRange(),
            maxPushConstantsSize(),
            maxMemoryAllocationCount(),
            maxSamplerAllocationCount(),
            bufferImageGranularity(),
            sparseAddressSpaceSize(),
            maxBoundDescriptorSets(),
            maxPerStageDescriptorSamplers(),
            maxPerStageDescriptorUniformBuffers(),
            maxPerStageDescriptorStorageBuffers(),
            maxPerStageDescriptorSampledImages(),
            maxPerStageDescriptorStorageImages(),
            maxPerStageDescriptorInputAttachments(),
            maxPerStageResources(),
            maxDescriptorSetSamplers(),
            maxDescriptorSetUniformBuffers(),
            maxDescriptorSetUniformBuffersDynamic(),
            maxDescriptorSetStorageBuffers(),
            maxDescriptorSetStorageBuffersDynamic(),
            maxDescriptorSetSampledImages(),
            maxDescriptorSetStorageImages(),
            maxDescriptorSetInputAttachments(),
            maxVertexInputAttributes(),
            maxVertexInputBindings(),
            maxVertexInputAttributeOffset(),
            maxVertexInputBindingStride(),
            maxVertexOutputComponents(),
            maxTessellationGenerationLevel(),
            maxTessellationPatchSize(),
            maxTessellationControlPerVertexInputComponents(),
            maxTessellationControlPerVertexOutputComponents(),
            maxTessellationControlPerPatchOutputComponents(),
            maxTessellationControlTotalOutputComponents(),
            maxTessellationEvaluationInputComponents(),
            maxTessellationEvaluationOutputComponents(),
            maxGeometryShaderInvocations(),
            maxGeometryInputComponents(),
            maxGeometryOutputComponents(),
            maxGeometryOutputVertices(),
            maxGeometryTotalOutputComponents(),
            maxFragmentInputComponents(),
            maxFragmentOutputAttachments(),
            maxFragmentDualSrcAttachments(),
            maxFragmentCombinedOutputResources(),
            maxComputeSharedMemorySize(),
            maxComputeWorkGroupCount().toIntArray(),
            maxComputeWorkGroupInvocations(),
            maxComputeWorkGroupSize().toIntArray(),
            subPixelPrecisionBits(),
            subTexelPrecisionBits(),
            mipmapPrecisionBits(),
            maxDrawIndexedIndexValue(),
            maxDrawIndirectCount(),
            maxSamplerLodBias(),
            maxSamplerAnisotropy(),
            maxViewports(),
            maxViewportDimensions().toIntArray(),
            viewportBoundsRange().toFloatArray(),
            viewportSubPixelBits(),
            minMemoryMapAlignment(),
            minTexelBufferOffsetAlignment(),
            minUniformBufferOffsetAlignment(),
            minStorageBufferOffsetAlignment(),
            minTexelOffset(),
            maxTexelOffset(),
            minTexelGatherOffset(),
            maxTexelGatherOffset(),
            minInterpolationOffset(),
            maxInterpolationOffset(),
            subPixelInterpolationOffsetBits(),
            maxFramebufferWidth(),
            maxFramebufferHeight(),
            maxFramebufferLayers(),
            VkSampleCountFlagBits.values().filter { it.bit and framebufferColorSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and framebufferDepthSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and framebufferStencilSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and framebufferNoAttachmentsSampleCounts() == it.bit },
            maxColorAttachments(),
            VkSampleCountFlagBits.values().filter { it.bit and sampledImageColorSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and sampledImageIntegerSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and sampledImageDepthSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and sampledImageStencilSampleCounts() == it.bit },
            VkSampleCountFlagBits.values().filter { it.bit and storageImageSampleCounts() == it.bit },
            maxSampleMaskWords(),
            timestampComputeAndGraphics(),
            timestampPeriod(),
            maxClipDistances(),
            maxCullDistances(),
            maxCombinedClipAndCullDistances(),
            discreteQueuePriorities(),
            pointSizeRange().toFloatArray(),
            lineWidthRange().toFloatArray(),
            pointSizeGranularity(),
            lineWidthGranularity(),
            strictLines(),
            standardSampleLocations(),
            optimalBufferCopyOffsetAlignment(),
            optimalBufferCopyRowPitchAlignment(),
            nonCoherentAtomSize())
}
